projects:
  Calorise:
    schemaPath: amplify/backend/api/Calorise/build/schema.graphql
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: eu-north-1
        apiId: null
        maxDepth: 2
